[phases.setup]
nixPkgs = [
  "php82",
  "php82Extensions.pdo_mysql",
  "php82Extensions.mbstring",
  "php82Extensions.curl",
  "php82Extensions.openssl",
  "php82Extensions.tokenizer",
  "php82Extensions.xml",
  "php82Extensions.dom",
  "php82Extensions.ctype",
  "php82Extensions.json"
]
